from MotorController import MotorController
from time import sleep

controller = MotorController()
sleep(1)
controller.moveAngles(-30, 0)
sleep(1)
controller.moveAngles(-30, -30)
sleep(1)
controller.moveAngles(0, -30)
sleep(1)
controller.moveAngles(30, -30)
sleep(1)
controller.moveAngles(30, 0)
sleep(1)
controller.moveAngles(30, 30)
sleep(1)
controller.moveAngles(0, 30)
sleep(1)
controller.moveAngles(-30, 30)
sleep(1)
controller.moveAngles(-30, 0)
sleep(1)
controller.moveAngles(0, 0)
sleep(1)
